version: '3.5'

services:
  mysql:
    image: mysql/mysql-server:5.7.21
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ptt
      - MYSQL_PASSWORD=ptt

  payara:
    ports:
      - "8088:8080"
      - "4849:4848"
      - "8182:8181"
    links:
      - mysql
    depends_on:
      - mysql
    build: .
      
  sonarqube:
    image: sonarqube
    command: -Dsonar.web.context=/sonar
    ports:
      - "9898:9000"