version: '3.5'

services:
  mysql:
    image: mysql/mysql-server:5.7.21
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ports:
      - "3390:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ptt
      - MYSQL_PASSWORD=ptt

  payara:
    build: .
    ports:
      - "8090:8080"
      - "4890:4848"
      - "8190:8181"
    links:
      - mysql
    depends_on:
      - mysql
