version: '3.5'

services:
  mysql:
    image: mysql/mysql-server:5.7.21
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ptt
      - MYSQL_PASSWORD=ptt

  payara:
    build: .
    ports:
      - "8088:8080"
      - "4849:4848"
      - "8182:8181"
    links:
      - mysql
    depends_on:
      - mysql
